version: '3.2'

services:
  traefik:
    image: traefik:latest
    container_name: traefik
    depends_on:
      - dockersock-proxy
    command: 
      - "--api"
      - "--certificatesResolvers.default.acme.email=${ACME_EMAIL}"
      - "--providers.docker.defaultrule=Host(`{{ trimSuffix `_config` .Name }}.${DOMAIN_BASE}`)"
    networks:
      - web
      - default
      - dockersock-traefik-proxy
    ports:
      - 80:80
      - 443:443
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.http.middlewares.traefikauth.basicauth.usersfile=/traefik.htpasswd"
      - "traefik.http.middlewares.redirectscheme.redirectscheme.scheme=https"
      - "traefik.http.middlewares.redirectscheme.redirectscheme.permanent=true"
      - "traefik.http.routers.traefik.entrypoints=http"
      - "traefik.http.routers.traefik-secured.entrypoints=https"
      - "traefik.http.routers.traefik-secured.tls=true"
      - "traefik.http.routers.traefik.middlewares=redirectscheme@docker"
      - "traefik.http.routers.traefik-secured.middlewares=traefikauth@docker"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
      - "com.centurylinklabs.watchtower.enable=true"
    volumes:
      - ${PERSISTENT_DIR}/traefik/traefik.toml:/traefik.toml
      - ${PERSISTENT_DIR}/traefik/acme.json:/acme.json
      - ${PERSISTENT_DIR}/traefik/traefik.htpasswd:/traefik.htpasswd
      - ${PERSISTENT_DIR}/traefik/log:/var/log
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    
  dockersock-proxy:
    image: tecnativa/docker-socket-proxy:latest
    container_name: dockersock-proxy
    environment:
      - CONTAINERS=1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - dockersock-traefik-proxy
    ports:
      - 2375
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    restart: unless-stopped

  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    command: --interval 900 --label-enable --cleanup
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    restart: unless-stopped

  fail2ban:
    image: crazymax/fail2ban:latest
    container_name: fail2ban
    network_mode: "host"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - ${PERSISTENT_DIR}/traefik/log:/var/log:ro
      - ${PERSISTENT_DIR}/fail2ban/data:/data
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    restart: unless-stopped

networks:
  web:
    external: true
  dockersock-traefik-proxy:
  default:
    driver: bridge
