[global]
  checkNewVersion = true
  sendAnonymousUsage = true

[entryPoints]
  [entryPoints.http]
    address = ":80"
  [entryPoints.https]
    address = ":443"
  [entryPoints.traefik]
    address = ":8080"

[providers]
  providersThrottleDuration = "2s"
  [providers.docker]
    watch = true
    endpoint = "tcp://dockersock-proxy:2375"
    exposedByDefault = false

[api]
  insecure = true
  dashboard = true

[log]
  filePath = "/var/log/traefik.log"
  level = "ERROR"

[accessLog]
  filePath = "/var/log/access.log"
  bufferingSize = 0
  [accessLog.filters]
    statusCodes = ["400-499"]
    minDuration = "0s"

[certificatesResolvers]
  [certificatesResolvers.default]
    [certificatesResolvers.default.acme]
      storage = "acme.json"
      #email = "" # set from docker-compose.yml
      [certificatesResolvers.default.acme.httpChallenge]
        entryPoint = "http"

# vim: tabstop=2 shiftwidth=2 expandtab
