debug = true
logLevel = "ERROR"

checkNewVersion = true
defaultEntryPoints = ["https","http"]

[entryPoints]
  [entryPoints.http]
    address = ":80"
    [entryPoints.http.redirect]
      entryPoint = "https"
      permanent = true
  [entryPoints.https]
    address = ":443"
    compress = true
    [entryPoints.https.tls]
  [entryPoints.traefik]
    address = ":8080"
    compress = true

[api]
  entryPoint = "traefik"
  dashboard = true

[accessLog]
  filePath = "/var/log/access.log"
  [accessLog.filters]
    statusCodes = ["400-499", "500-599"]
[retry]

[docker]
  endpoint = "tcp://dockersock-proxy:2375"
  #domain = ""  # set from docker-compose.yml
  watch = true
  exposedByDefault = false

[acme]
  #email = ""  # set from docker-compose.yml
  storage = "acme.json"
  entryPoint = "https"
  onHostRule = true
  [acme.httpChallenge]
    entryPoint = "http"

# vim: tabstop=2 shiftwidth=2 expandtab
